global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dspy-applications'
    static_configs:
      - targets: ['dspy-guide:8000']
    scrape_interval: 5s
    metrics_path: /metrics
    
  - job_name: 'dspy-local'
    static_configs: 
      - targets: ['localhost:8000']
    scrape_interval: 5s
    metrics_path: /metrics